# Generated by Django 2.2.6 on 2019-10-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemonstar_user',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daemonstar_user',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
