# Generated by Django 2.2.6 on 2019-10-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191014_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemonstar_user',
            name='user_avatar',
            field=models.ImageField(blank=True, default='/media/profiles/8f3e4b6d2f299e6dc8911615f60271eb_k8LIJkL.jpg', upload_to='profiles'),
        ),
    ]
