# Generated by Django 2.2.6 on 2019-10-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20191016_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemonstar_user',
            name='user_avatar',
            field=models.ImageField(blank=True, default='/media/profiles/3.jpg', upload_to='profiles'),
        ),
    ]
